// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonIdentificationSystem.API;

#nullable disable

namespace PersonIdentificationSystem.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317180246_initial-setup")]
    partial class initialsetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.Detection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("DetectionTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detection_timestamp");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean")
                        .HasColumnName("email_sent");

                    b.Property<string>("FrameImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("frame_image_url");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("RawMatchData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_match_data");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text")
                        .HasColumnName("verification_notes");

                    b.Property<string>("VerificationStatus")
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("pk_detections");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_detections_person_id");

                    b.HasIndex("StreamId")
                        .HasDatabaseName("ix_detections_stream_id");

                    b.ToTable("detections", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DetectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("detection_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient_email");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("SentTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_notification_logs");

                    b.HasIndex("DetectionId")
                        .HasDatabaseName("ix_notification_logs_detection_id");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FromEmail")
                        .HasColumnType("text")
                        .HasColumnName("from_email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<decimal>("MinimumConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("minimum_confidence");

                    b.Property<string[]>("NotifyOnRiskLevels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("notify_on_risk_levels");

                    b.Property<int>("RateLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_minutes");

                    b.Property<string[]>("RecipientEmails")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipient_emails");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text")
                        .HasColumnName("smtp_host");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<bool?>("SmtpUseTls")
                        .HasColumnType("boolean")
                        .HasColumnName("smtp_use_tls");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_settings");

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DateUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("risk_level");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.PersonPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<decimal?>("QualityScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("quality_score");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.HasKey("Id")
                        .HasName("pk_person_photos");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_photos_person_id");

                    b.ToTable("person_photos", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.RTSPStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CameraLocation")
                        .HasColumnType("text")
                        .HasColumnName("camera_location");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("camera_name");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<int>("FrameIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("frame_interval_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<string>("RtspUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rtsp_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rtsp_streams");

                    b.ToTable("rtsp_streams", (string)null);
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.Detection", b =>
                {
                    b.HasOne("PersonIdentificationSystem.API.Models.Entities.Person", "Person")
                        .WithMany("Detections")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_detections_persons_person_id");

                    b.HasOne("PersonIdentificationSystem.API.Models.Entities.RTSPStream", "Stream")
                        .WithMany("Detections")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_detections_rtsp_streams_stream_id");

                    b.Navigation("Person");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.NotificationLog", b =>
                {
                    b.HasOne("PersonIdentificationSystem.API.Models.Entities.Detection", "Detection")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("DetectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_logs_detections_detection_id");

                    b.Navigation("Detection");
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.PersonPhoto", b =>
                {
                    b.HasOne("PersonIdentificationSystem.API.Models.Entities.Person", "Person")
                        .WithMany("Photos")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_photos_persons_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.Detection", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.Person", b =>
                {
                    b.Navigation("Detections");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("PersonIdentificationSystem.API.Models.Entities.RTSPStream", b =>
                {
                    b.Navigation("Detections");
                });
#pragma warning restore 612, 618
        }
    }
}
